package com.love.Mapper;

import com.love.module.Important_history;
import com.love.module.Important_historyExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface Important_historyMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table important_history
     *
     * @mbg.generated Wed Oct 19 18:43:23 CST 2022
     */
    long countByExample(Important_historyExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table important_history
     *
     * @mbg.generated Wed Oct 19 18:43:23 CST 2022
     */
    int deleteByExample(Important_historyExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table important_history
     *
     * @mbg.generated Wed Oct 19 18:43:23 CST 2022
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table important_history
     *
     * @mbg.generated Wed Oct 19 18:43:23 CST 2022
     */
    int insert(Important_history record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table important_history
     *
     * @mbg.generated Wed Oct 19 18:43:23 CST 2022
     */
    int insertSelective(Important_history record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table important_history
     *
     * @mbg.generated Wed Oct 19 18:43:23 CST 2022
     */
    List<Important_history> selectByExample(Important_historyExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table important_history
     *
     * @mbg.generated Wed Oct 19 18:43:23 CST 2022
     */
    Important_history selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table important_history
     *
     * @mbg.generated Wed Oct 19 18:43:23 CST 2022
     */
    int updateByExampleSelective(@Param("record") Important_history record, @Param("example") Important_historyExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table important_history
     *
     * @mbg.generated Wed Oct 19 18:43:23 CST 2022
     */
    int updateByExample(@Param("record") Important_history record, @Param("example") Important_historyExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table important_history
     *
     * @mbg.generated Wed Oct 19 18:43:23 CST 2022
     */
    int updateByPrimaryKeySelective(Important_history record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table important_history
     *
     * @mbg.generated Wed Oct 19 18:43:23 CST 2022
     */
    int updateByPrimaryKey(Important_history record);
}