package com.love.Mapper;

import com.love.module.Scenes;
import com.love.module.ScenesExample;
import java.util.List;

import org.apache.ibatis.annotations.Mapper;
import org.apache.ibatis.annotations.Param;

@Mapper
public interface ScenesMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table scenes
     *
     * @mbg.generated Sun Mar 12 19:26:14 CST 2023
     */
    long countByExample(ScenesExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table scenes
     *
     * @mbg.generated Sun Mar 12 19:26:14 CST 2023
     */
    int deleteByExample(ScenesExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table scenes
     *
     * @mbg.generated Sun Mar 12 19:26:14 CST 2023
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table scenes
     *
     * @mbg.generated Sun Mar 12 19:26:14 CST 2023
     */
    int insert(Scenes record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table scenes
     *
     * @mbg.generated Sun Mar 12 19:26:14 CST 2023
     */
    int insertSelective(Scenes record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table scenes
     *
     * @mbg.generated Sun Mar 12 19:26:14 CST 2023
     */
    List<Scenes> selectByExample(ScenesExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table scenes
     *
     * @mbg.generated Sun Mar 12 19:26:14 CST 2023
     */
    Scenes selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table scenes
     *
     * @mbg.generated Sun Mar 12 19:26:14 CST 2023
     */
    int updateByExampleSelective(@Param("record") Scenes record, @Param("example") ScenesExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table scenes
     *
     * @mbg.generated Sun Mar 12 19:26:14 CST 2023
     */
    int updateByExample(@Param("record") Scenes record, @Param("example") ScenesExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table scenes
     *
     * @mbg.generated Sun Mar 12 19:26:14 CST 2023
     */
    int updateByPrimaryKeySelective(Scenes record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table scenes
     *
     * @mbg.generated Sun Mar 12 19:26:14 CST 2023
     */
    int updateByPrimaryKey(Scenes record);
}