package com.love.Mapper;

import com.love.module.Small_notes_kudos;
import com.love.module.Small_notes_kudosExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface Small_notes_kudosMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table small_notes_kudos
     *
     * @mbg.generated Wed Oct 19 18:43:22 CST 2022
     */
    long countByExample(Small_notes_kudosExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table small_notes_kudos
     *
     * @mbg.generated Wed Oct 19 18:43:22 CST 2022
     */
    int deleteByExample(Small_notes_kudosExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table small_notes_kudos
     *
     * @mbg.generated Wed Oct 19 18:43:22 CST 2022
     */
    int insert(Small_notes_kudos record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table small_notes_kudos
     *
     * @mbg.generated Wed Oct 19 18:43:22 CST 2022
     */
    int insertSelective(Small_notes_kudos record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table small_notes_kudos
     *
     * @mbg.generated Wed Oct 19 18:43:22 CST 2022
     */
    List<Small_notes_kudos> selectByExample(Small_notes_kudosExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table small_notes_kudos
     *
     * @mbg.generated Wed Oct 19 18:43:22 CST 2022
     */
    int updateByExampleSelective(@Param("record") Small_notes_kudos record, @Param("example") Small_notes_kudosExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table small_notes_kudos
     *
     * @mbg.generated Wed Oct 19 18:43:22 CST 2022
     */
    int updateByExample(@Param("record") Small_notes_kudos record, @Param("example") Small_notes_kudosExample example);
}