package com.love.Mapper;

import com.love.module.Small_notes;
import com.love.module.Small_notesExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface Small_notesMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table small_notes
     *
     * @mbg.generated Wed Oct 19 18:43:22 CST 2022
     */
    long countByExample(Small_notesExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table small_notes
     *
     * @mbg.generated Wed Oct 19 18:43:22 CST 2022
     */
    int deleteByExample(Small_notesExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table small_notes
     *
     * @mbg.generated Wed Oct 19 18:43:22 CST 2022
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table small_notes
     *
     * @mbg.generated Wed Oct 19 18:43:22 CST 2022
     */
    int insert(Small_notes record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table small_notes
     *
     * @mbg.generated Wed Oct 19 18:43:22 CST 2022
     */
    int insertSelective(Small_notes record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table small_notes
     *
     * @mbg.generated Wed Oct 19 18:43:22 CST 2022
     */
    List<Small_notes> selectByExampleWithBLOBs(Small_notesExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table small_notes
     *
     * @mbg.generated Wed Oct 19 18:43:22 CST 2022
     */
    List<Small_notes> selectByExample(Small_notesExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table small_notes
     *
     * @mbg.generated Wed Oct 19 18:43:22 CST 2022
     */
    Small_notes selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table small_notes
     *
     * @mbg.generated Wed Oct 19 18:43:22 CST 2022
     */
    int updateByExampleSelective(@Param("record") Small_notes record, @Param("example") Small_notesExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table small_notes
     *
     * @mbg.generated Wed Oct 19 18:43:22 CST 2022
     */
    int updateByExampleWithBLOBs(@Param("record") Small_notes record, @Param("example") Small_notesExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table small_notes
     *
     * @mbg.generated Wed Oct 19 18:43:22 CST 2022
     */
    int updateByExample(@Param("record") Small_notes record, @Param("example") Small_notesExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table small_notes
     *
     * @mbg.generated Wed Oct 19 18:43:22 CST 2022
     */
    int updateByPrimaryKeySelective(Small_notes record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table small_notes
     *
     * @mbg.generated Wed Oct 19 18:43:22 CST 2022
     */
    int updateByPrimaryKeyWithBLOBs(Small_notes record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table small_notes
     *
     * @mbg.generated Wed Oct 19 18:43:22 CST 2022
     */
    int updateByPrimaryKey(Small_notes record);
}