package com.love.Mapper;

import com.love.module.User_id_card;
import com.love.module.User_id_cardExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface User_id_cardMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_id_card
     *
     * @mbg.generated Wed Oct 19 18:43:22 CST 2022
     */
    long countByExample(User_id_cardExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_id_card
     *
     * @mbg.generated Wed Oct 19 18:43:22 CST 2022
     */
    int deleteByExample(User_id_cardExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_id_card
     *
     * @mbg.generated Wed Oct 19 18:43:22 CST 2022
     */
    int insert(User_id_card record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_id_card
     *
     * @mbg.generated Wed Oct 19 18:43:22 CST 2022
     */
    int insertSelective(User_id_card record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_id_card
     *
     * @mbg.generated Wed Oct 19 18:43:22 CST 2022
     */
    List<User_id_card> selectByExample(User_id_cardExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_id_card
     *
     * @mbg.generated Wed Oct 19 18:43:22 CST 2022
     */
    int updateByExampleSelective(@Param("record") User_id_card record, @Param("example") User_id_cardExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_id_card
     *
     * @mbg.generated Wed Oct 19 18:43:22 CST 2022
     */
    int updateByExample(@Param("record") User_id_card record, @Param("example") User_id_cardExample example);
}