package com.love.module;

public class Companion_pplication_list {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column companion_pplication_list.id
     *
     * @mbg.generated Wed Oct 19 18:43:23 CST 2022
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column companion_pplication_list.user_id
     *
     * @mbg.generated Wed Oct 19 18:43:23 CST 2022
     */
    private Integer userId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column companion_pplication_list.applicant_id
     *
     * @mbg.generated Wed Oct 19 18:43:23 CST 2022
     */
    private Integer applicantId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column companion_pplication_list.id
     *
     * @return the value of companion_pplication_list.id
     *
     * @mbg.generated Wed Oct 19 18:43:23 CST 2022
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column companion_pplication_list.id
     *
     * @param id the value for companion_pplication_list.id
     *
     * @mbg.generated Wed Oct 19 18:43:23 CST 2022
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column companion_pplication_list.user_id
     *
     * @return the value of companion_pplication_list.user_id
     *
     * @mbg.generated Wed Oct 19 18:43:23 CST 2022
     */
    public Integer getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column companion_pplication_list.user_id
     *
     * @param userId the value for companion_pplication_list.user_id
     *
     * @mbg.generated Wed Oct 19 18:43:23 CST 2022
     */
    public void setUserId(Integer userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column companion_pplication_list.applicant_id
     *
     * @return the value of companion_pplication_list.applicant_id
     *
     * @mbg.generated Wed Oct 19 18:43:23 CST 2022
     */
    public Integer getApplicantId() {
        return applicantId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column companion_pplication_list.applicant_id
     *
     * @param applicantId the value for companion_pplication_list.applicant_id
     *
     * @mbg.generated Wed Oct 19 18:43:23 CST 2022
     */
    public void setApplicantId(Integer applicantId) {
        this.applicantId = applicantId;
    }
}