package com.love.module;

public class Scenes {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column scenes.id
     *
     * @mbg.generated Sun Mar 12 19:26:14 CST 2023
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column scenes.name
     *
     * @mbg.generated Sun Mar 12 19:26:14 CST 2023
     */
    private String name;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column scenes.portfolio
     *
     * @mbg.generated Sun Mar 12 19:26:14 CST 2023
     */
    private String portfolio;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column scenes.id
     *
     * @return the value of scenes.id
     *
     * @mbg.generated Sun Mar 12 19:26:14 CST 2023
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column scenes.id
     *
     * @param id the value for scenes.id
     *
     * @mbg.generated Sun Mar 12 19:26:14 CST 2023
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column scenes.name
     *
     * @return the value of scenes.name
     *
     * @mbg.generated Sun Mar 12 19:26:14 CST 2023
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column scenes.name
     *
     * @param name the value for scenes.name
     *
     * @mbg.generated Sun Mar 12 19:26:14 CST 2023
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column scenes.portfolio
     *
     * @return the value of scenes.portfolio
     *
     * @mbg.generated Sun Mar 12 19:26:14 CST 2023
     */
    public String getPortfolio() {
        return portfolio;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column scenes.portfolio
     *
     * @param portfolio the value for scenes.portfolio
     *
     * @mbg.generated Sun Mar 12 19:26:14 CST 2023
     */
    public void setPortfolio(String portfolio) {
        this.portfolio = portfolio == null ? null : portfolio.trim();
    }
}