package com.love.module;

public class Small_notes_kudos {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column small_notes_kudos.id
     *
     * @mbg.generated Wed Oct 19 18:43:22 CST 2022
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column small_notes_kudos.small_notes_id
     *
     * @mbg.generated Wed Oct 19 18:43:22 CST 2022
     */
    private Integer smallNotesId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column small_notes_kudos.id
     *
     * @return the value of small_notes_kudos.id
     *
     * @mbg.generated Wed Oct 19 18:43:22 CST 2022
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column small_notes_kudos.id
     *
     * @param id the value for small_notes_kudos.id
     *
     * @mbg.generated Wed Oct 19 18:43:22 CST 2022
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column small_notes_kudos.small_notes_id
     *
     * @return the value of small_notes_kudos.small_notes_id
     *
     * @mbg.generated Wed Oct 19 18:43:22 CST 2022
     */
    public Integer getSmallNotesId() {
        return smallNotesId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column small_notes_kudos.small_notes_id
     *
     * @param smallNotesId the value for small_notes_kudos.small_notes_id
     *
     * @mbg.generated Wed Oct 19 18:43:22 CST 2022
     */
    public void setSmallNotesId(Integer smallNotesId) {
        this.smallNotesId = smallNotesId;
    }
}