package com.love.module;

public class User_id_card {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_id_card.user_id
     *
     * @mbg.generated Wed Oct 19 18:43:22 CST 2022
     */
    private Integer userId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_id_card.real_name
     *
     * @mbg.generated Wed Oct 19 18:43:22 CST 2022
     */
    private String realName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_id_card.id_number
     *
     * @mbg.generated Wed Oct 19 18:43:22 CST 2022
     */
    private String idNumber;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_id_card.user_id
     *
     * @return the value of user_id_card.user_id
     *
     * @mbg.generated Wed Oct 19 18:43:22 CST 2022
     */
    public Integer getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_id_card.user_id
     *
     * @param userId the value for user_id_card.user_id
     *
     * @mbg.generated Wed Oct 19 18:43:22 CST 2022
     */
    public void setUserId(Integer userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_id_card.real_name
     *
     * @return the value of user_id_card.real_name
     *
     * @mbg.generated Wed Oct 19 18:43:22 CST 2022
     */
    public String getRealName() {
        return realName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_id_card.real_name
     *
     * @param realName the value for user_id_card.real_name
     *
     * @mbg.generated Wed Oct 19 18:43:22 CST 2022
     */
    public void setRealName(String realName) {
        this.realName = realName == null ? null : realName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_id_card.id_number
     *
     * @return the value of user_id_card.id_number
     *
     * @mbg.generated Wed Oct 19 18:43:22 CST 2022
     */
    public String getIdNumber() {
        return idNumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_id_card.id_number
     *
     * @param idNumber the value for user_id_card.id_number
     *
     * @mbg.generated Wed Oct 19 18:43:22 CST 2022
     */
    public void setIdNumber(String idNumber) {
        this.idNumber = idNumber == null ? null : idNumber.trim();
    }
}