package com.love.module;

import java.util.Date;

public class User_love {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_love.user_id
     *
     * @mbg.generated Wed Oct 19 18:43:22 CST 2022
     */
    private Integer userId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_love.love_id
     *
     * @mbg.generated Wed Oct 19 18:43:22 CST 2022
     */
    private Integer loveId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_love.userlove_time
     *
     * @mbg.generated Wed Oct 19 18:43:22 CST 2022
     */
    private Date userloveTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_love.user_id
     *
     * @return the value of user_love.user_id
     *
     * @mbg.generated Wed Oct 19 18:43:22 CST 2022
     */
    public Integer getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_love.user_id
     *
     * @param userId the value for user_love.user_id
     *
     * @mbg.generated Wed Oct 19 18:43:22 CST 2022
     */
    public void setUserId(Integer userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_love.love_id
     *
     * @return the value of user_love.love_id
     *
     * @mbg.generated Wed Oct 19 18:43:22 CST 2022
     */
    public Integer getLoveId() {
        return loveId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_love.love_id
     *
     * @param loveId the value for user_love.love_id
     *
     * @mbg.generated Wed Oct 19 18:43:22 CST 2022
     */
    public void setLoveId(Integer loveId) {
        this.loveId = loveId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_love.userlove_time
     *
     * @return the value of user_love.userlove_time
     *
     * @mbg.generated Wed Oct 19 18:43:22 CST 2022
     */
    public Date getUserloveTime() {
        return userloveTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_love.userlove_time
     *
     * @param userloveTime the value for user_love.userlove_time
     *
     * @mbg.generated Wed Oct 19 18:43:22 CST 2022
     */
    public void setUserloveTime(Date userloveTime) {
        this.userloveTime = userloveTime;
    }
}